import express from 'express';
import cors from 'cors';
import { generateSpec } from './generate-openapi';
import swaggerUi from 'swagger-ui-express';
import * as routes from './routes';

const app = express();

app.use(cors());
app.use(express.json());
routes.register(app);

// Generate OpenAPI spec based on the comments in the code of this project, including this file!
const openapiSpec = generateSpec();
// Print the result for debugging in the console
console.log(openapiSpec);

/**
 * @openapi
 * /openapi:
 *   get:
 *     description: Get OpenAPI spec
 *     tags: [OpenAPI]
 *     responses:
 *       200:
 *         description: Returns the OpenAPI spec for this project.
 */
app.get('/openapi', (req, res) => res.send(openapiSpec));

// Set up Swagger UI to display the generated OpenAPI spec
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(openapiSpec));

// Default / to the api docs generated by Swagger UI
app.get('/', (req, res) => {
  res.redirect('/api-docs');
});

app.listen(8080, () => {
  console.log(`server started at http://localhost:8080`);
});
